### ISSUE TITLE
This is NOT Monad

### ISSUE THREAD

**Issue by bleis-tift** [phlik/Monads.net#5]
Please read the document about monad.
for example, [All About Monads](http://www.haskell.org/haskellwiki/All_about_monads) and [Monad laws](http://www.haskell.org/haskellwiki/Monad_laws)

Where is the definition of bind function?
Where is the definition of return function?
In C#, these functions correspond to the Select method and SelectMany method, but not exist.

This library does not provide any monads...

**Comment by phlik** [comment]
Thanks.  Will keep that in mind please feel free to build your own version of the Maybe Monad and make it easy to use in C# I welcome the leanings I can gain from you work.

**Comment by bleis-tift** [comment]
Already, I have [my own version of the Option Monad](https://github.com/LangExt/LangExt).

**Comment by squirrelsama** [comment]
Technically, you're correct bleis-tift. In fact, I had this conversation with phlik a couple days ago.

Because C# doesn't support pattern-matching, it was decided that usability in C# would increase if the behavior of the Maybe monad (a.k.a. F# option<T>) was abstracted. 

In this library, null is considered the None value, and a value other than null is considered the Some value.

In this way, boxing into an Option<T> or Maybe<T> class is avoided, and consuming this implementation is cleaner.

The unfortunate side-effect is that it only works with reference-types, not value-types, hence the "Let" functions that work on value-types, that require a "failureValue".

**Comment by LlamaSantos** [comment]
I will echo squirrelsama's sentiment and add some clarifying points.

We initially had implemented the library with Option in order to support Some/None, however in order to support it properly the code rapidly expanded and the public interface was very cumbersome and undesirable.  What we wanted was something that was extremely native feeling towards .Net developers and still provided the stability that a Monad could provide.  What we finished with was something that stayed true to what the the Maybe Monad provides us in a Functional language with the practicality that .Net developers could use with little to no ceremony.

squirrelsama correctly identified the one lacking that we have in that the library will only support types derived from ReferenceType and we left ValueTypes to be handled.  We felt this was ok.  Rarely in my 13+ years of .Net development are we met with a null ValueType of any significant meaning and that Nullable<T> and some extensions built around that were more than adequate.

The final thing I'd like to address is what the Maybe Monad does functionally.  In essence it checks for a value and does some action if "Some" value is found, otherwise bypasses every other statement in the execution chain.  This is functionally what Monads.Net does.  The form isn't perfect especially when one uses the Haskell documentation ;-)  but the function is.

We appreciate any constructive feedback that can make Monads.Net a better library for all .Net developers to use.

**Comment by bleis-tift** [comment]
@squirrelsama 

> Because C# doesn't support pattern-matching, it was decided that usability in C# would increase if the behavior of the Maybe monad (a.k.a. F# option) was abstracted.

Pattern-matching is very very useful. But it is NOT the essence of Moand.
In addition, we can support in [a limited way in C#](https://github.com/LangExt/LangExt/blob/master/LangExt.Tests/OptionTest.cs#L234).

> In this library, null is considered the None value, and a value other than null is considered the Some value.

One of the advantages of the Maybe monad, is that you can eliminate the NRE(in C#!).
But it is not possible in this library.

> In this way, boxing into an Option or Maybe class is avoided, and consuming this implementation is cleaner.
> 
> The unfortunate side-effect is that it only works with reference-types, not value-types, hence the "Let" functions that work on value-types, that require a "failureValue".

I can not understand.
May I ask a little more explanation?

@LlamaSantos 
Why this library is named "Monads.net"?
This library has only pseudo Maybe Monad.
I think better to change the name will not occur misunderstanding.

Sorry, I'm sleepy. Because I live in Japan.
So I need your help tomorrow continued.

**Comment by heneryville** [comment]
You know, he actually does bring up a good point about the name. This isn't really an implementation of monads as it is an implementation of the ever popular Maybe monad. Perhaps a better name would be Maybe.Net.

**Comment by mausch** [comment]
It seems this project has the same problems I explained in this other project https://github.com/sergun/monads.net/issues/1 (I wonder if these projects are somehow related?). Bottom line: it's not a monad, it's not the Maybe monad.

**Comment by phlik** [comment]
@mausch That's fine I don't think I will be changing the name. Have a good day.

**Comment by heneryville** [comment]
@bleis-tift @mausch If you're looking for a true-blue maybe monad implementation https://github.com/Strilanc/May may be a good alternative. I much prefer the terser implementation found in this library which uses null as an approximation for the Maybe Nothing.  The other library uses a wrapper, as many other implementations do.

**Comment by LlamaSantos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdf](https://trello.com/c/cYsAGwiH/1-asdf)
